config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :countries, only: [:index, :show] do
    resources :plans, only: [:show]
  end

  root to: 'countries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  has_and_belongs_to_many :plans

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/country.rb
class Country < ApplicationRecord

  has_many :plans, foreign_key: :countries_id

  scope :with_plans, -> { where(id: Plan.distinct(:countries_id).pluck(:countries_id))}
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_and_belongs_to_many :benefits
  belongs_to :country, foreign_key: "countries_id", required: true, inverse_of: :plans

  validates :price_hundredths, numericality: {greater_than: 0, only_integer: true}
  validates :name, presence: true, uniqueness: { scope: :country}
  validates :description, presence: true
  validates :benefits, presence: true

  def price
    "#{format('%.2f', price_hundredths / 100.0)} #{country.currency}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.with_plans.all
  end

  def show
    @plans = Plan.where(countries_id: params[:id]).all
    if @plans.blank?
      render plain: "Not Found", status: :not_found
    else
      respond_to do |format|
        format.html
        format.json { render json: plans_as_json, layout: false }
      end
    end
  end

private

  def plans_as_json
    @plans.map { |x| x.as_json(only: [:id, :name], methods: [:price]) }
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def show
    if @plan = Plan.where(countries_id: params[:country_id], id: params[:id]).first
      respond_to do |format|
        format.html
        format.json { render json: plan_as_json, layout: false }
      end
    else
      render plain: "Not Found", status: :not_found
    end
  end

private

  def plan_as_json
    @plan.as_json(methods: :price,
                  only: [:id, :name],
                  include: {benefits: {only: [:name, :description]}})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/countries/index.html.erb
<ul>
<% @countries.each do |country| %>
  <li><%= link_to(country.id, country_path(country)) %></li>
<% end %>
</ul>

app/views/countries/show.html.erb
<ul>
  <% @plans.each do |plan| %>
    <li>
      <h4>
        <%= link_to(plan.name, country_plan_path(id: plan.id, country_id: plan.country.id)) %>
      </h4>
      <p>
        <%= plan.price %>
      </p>
      <%= button_tag("subscribe") %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LegalExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/show.html.erb
<p>
  <%= @plan.description %>
</p>
<ul>
  <% @plan.benefits.each do |benefit|  %>
    <li>
      <h5>
        <%= benefit.name %>
      </h5>
      <p>
        <%= benefit.description %>
      </p>
    </li>
  <% end %>
</ul>